/**
 * spotify_auth.ts
 *
 * One-time Spotify OAuth setup. Spins up a local server on port 8888,
 * opens the Spotify authorization page, catches the callback, exchanges
 * the code for tokens, and appends SPOTIFY_REFRESH_TOKEN to .env.local.
 *
 * Usage:  npx tsx scripts/spotify_auth.ts
 */

import http from "http";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

dotenv.config({ path: path.join(process.cwd(), ".env.local") });

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET;
const REDIRECT_URI = "http://127.0.0.1:8888/callback";
const SCOPES = "user-read-recently-played user-read-playback-state";
const ENV_FILE = path.join(process.cwd(), ".env.local");

if (!CLIENT_ID || !CLIENT_SECRET) {
  console.error("Set SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET in .env.local first.");
  process.exit(1);
}

const authUrl =
  `https://accounts.spotify.com/authorize?` +
  `client_id=${CLIENT_ID}` +
  `&response_type=code` +
  `&redirect_uri=${encodeURIComponent(REDIRECT_URI)}` +
  `&scope=${encodeURIComponent(SCOPES)}`;

console.log("Opening Spotify authorization page...");
console.log(`If it doesn't open automatically, visit:\n${authUrl}\n`);

try {
  execSync(`open "${authUrl}"`);
} catch {
  // non-fatal, user can open manually
}

const server = http.createServer(async (req, res) => {
  if (!req.url?.startsWith("/callback")) {
    res.writeHead(404);
    res.end("Not found");
    return;
  }

  const url = new URL(req.url, `http://127.0.0.1:8888`);
  const code = url.searchParams.get("code");
  const error = url.searchParams.get("error");

  if (error || !code) {
    res.writeHead(400, { "Content-Type": "text/html" });
    res.end(`<h2>Authorization failed</h2><p>${error ?? "No code received"}</p>`);
    server.close();
    process.exit(1);
  }

  // Exchange code for tokens
  const credentials = Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString("base64");

  const tokenRes = await fetch("https://accounts.spotify.com/api/token", {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: REDIRECT_URI,
    }),
  });

  if (!tokenRes.ok) {
    const body = await tokenRes.text();
    res.writeHead(500, { "Content-Type": "text/html" });
    res.end(`<h2>Token exchange failed</h2><pre>${body}</pre>`);
    server.close();
    process.exit(1);
  }

  const tokens = (await tokenRes.json()) as {
    access_token: string;
    refresh_token: string;
    expires_in: number;
    scope: string;
  };

  // Write refresh token to .env.local
  let envContent = fs.readFileSync(ENV_FILE, "utf-8");

  if (envContent.includes("SPOTIFY_REFRESH_TOKEN=")) {
    envContent = envContent.replace(
      /SPOTIFY_REFRESH_TOKEN=.*/,
      `SPOTIFY_REFRESH_TOKEN=${tokens.refresh_token}`
    );
  } else {
    envContent += `\n# Spotify refresh token (auto-generated by spotify_auth.ts)\nSPOTIFY_REFRESH_TOKEN=${tokens.refresh_token}\n`;
  }

  fs.writeFileSync(ENV_FILE, envContent);

  console.log("\nRefresh token saved to .env.local");
  console.log("You can now run: npm run spotify:rebuild");

  res.writeHead(200, { "Content-Type": "text/html" });
  res.end(
    `<h2>Done!</h2>` +
    `<p>Refresh token saved to .env.local. You can close this tab.</p>` +
    `<p>Run <code>npm run spotify:rebuild</code> to pull your recent plays.</p>`
  );

  server.close();
  process.exit(0);
});

server.listen(8888, () => {
  console.log("Listening on http://127.0.0.1:8888/callback ...");
});
